@startuml

title cc_rpc building blocks overview
actor Client as "domain specific \nclient interface"
interface ClientStub
component ClientRPC <<library>>
interface IClientTransport
component ClientTransport <<library>>
component HttpClientLib <<external,library>>

component ServerTransport <<library>>
interface IServerTransport 
component HttpServerLib <<external,library>>
component ServerRPC <<library>>
interface ServerStub

Client --( ClientStub
ClientStub -- ClientRPC
ClientRPC--(IClientTransport
ClientTransport .down.> HttpClientLib : use
IClientTransport -- ClientTransport

IServerTransport--ServerTransport
ServerRPC--(IServerTransport
ServerStub--ServerRPC
actor Server as "domain specific \n interface server" 

Server<--ServerStub

ServerTransport .down.> HttpServerLib : use
HttpClientLib <.> HttpServerLib: wire transport

@enduml